// Generated by scripts/prepare-responsive-images.mjs.
// Keep original files in public/images; page images use these responsive WebP variants.
export type ResponsiveImageEntry = {
  widths: readonly number[];
  variants: Readonly<Record<number, string>>;
};

export const responsiveImageManifest: Readonly<Record<string, ResponsiveImageEntry>> = {
  "/images/drawing-12-14-16-type.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      546
    ],
    "variants": {
      "64": "/images/optimized/drawing-12-14-16-type-64.webp",
      "96": "/images/optimized/drawing-12-14-16-type-96.webp",
      "128": "/images/optimized/drawing-12-14-16-type-128.webp",
      "256": "/images/optimized/drawing-12-14-16-type-256.webp",
      "384": "/images/optimized/drawing-12-14-16-type-384.webp",
      "390": "/images/optimized/drawing-12-14-16-type-390.webp",
      "546": "/images/optimized/drawing-12-14-16-type-546.webp"
    }
  },
  "/images/drawing-20-type.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      825
    ],
    "variants": {
      "64": "/images/optimized/drawing-20-type-64.webp",
      "96": "/images/optimized/drawing-20-type-96.webp",
      "128": "/images/optimized/drawing-20-type-128.webp",
      "256": "/images/optimized/drawing-20-type-256.webp",
      "384": "/images/optimized/drawing-20-type-384.webp",
      "390": "/images/optimized/drawing-20-type-390.webp",
      "640": "/images/optimized/drawing-20-type-640.webp",
      "768": "/images/optimized/drawing-20-type-768.webp",
      "825": "/images/optimized/drawing-20-type-825.webp"
    }
  },
  "/images/drawing-bearing-reference.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      825
    ],
    "variants": {
      "64": "/images/optimized/drawing-bearing-reference-64.webp",
      "96": "/images/optimized/drawing-bearing-reference-96.webp",
      "128": "/images/optimized/drawing-bearing-reference-128.webp",
      "256": "/images/optimized/drawing-bearing-reference-256.webp",
      "384": "/images/optimized/drawing-bearing-reference-384.webp",
      "390": "/images/optimized/drawing-bearing-reference-390.webp",
      "640": "/images/optimized/drawing-bearing-reference-640.webp",
      "768": "/images/optimized/drawing-bearing-reference-768.webp",
      "825": "/images/optimized/drawing-bearing-reference-825.webp"
    }
  },
  "/images/factory-exterior.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1920
    ],
    "variants": {
      "64": "/images/optimized/factory-exterior-64.webp",
      "96": "/images/optimized/factory-exterior-96.webp",
      "128": "/images/optimized/factory-exterior-128.webp",
      "256": "/images/optimized/factory-exterior-256.webp",
      "384": "/images/optimized/factory-exterior-384.webp",
      "390": "/images/optimized/factory-exterior-390.webp",
      "640": "/images/optimized/factory-exterior-640.webp",
      "768": "/images/optimized/factory-exterior-768.webp",
      "1024": "/images/optimized/factory-exterior-1024.webp",
      "1280": "/images/optimized/factory-exterior-1280.webp",
      "1440": "/images/optimized/factory-exterior-1440.webp",
      "1920": "/images/optimized/factory-exterior-1920.webp"
    }
  },
  "/images/hinge-adjustable.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-adjustable-64.webp",
      "96": "/images/optimized/hinge-adjustable-96.webp",
      "128": "/images/optimized/hinge-adjustable-128.webp",
      "256": "/images/optimized/hinge-adjustable-256.webp",
      "384": "/images/optimized/hinge-adjustable-384.webp",
      "390": "/images/optimized/hinge-adjustable-390.webp",
      "640": "/images/optimized/hinge-adjustable-640.webp",
      "768": "/images/optimized/hinge-adjustable-768.webp",
      "800": "/images/optimized/hinge-adjustable-800.webp"
    }
  },
  "/images/hinge-bearing-detail.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-bearing-detail-64.webp",
      "96": "/images/optimized/hinge-bearing-detail-96.webp",
      "128": "/images/optimized/hinge-bearing-detail-128.webp",
      "256": "/images/optimized/hinge-bearing-detail-256.webp",
      "384": "/images/optimized/hinge-bearing-detail-384.webp",
      "390": "/images/optimized/hinge-bearing-detail-390.webp",
      "640": "/images/optimized/hinge-bearing-detail-640.webp",
      "768": "/images/optimized/hinge-bearing-detail-768.webp",
      "800": "/images/optimized/hinge-bearing-detail-800.webp"
    }
  },
  "/images/hinge-bearing.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-bearing-64.webp",
      "96": "/images/optimized/hinge-bearing-96.webp",
      "128": "/images/optimized/hinge-bearing-128.webp",
      "256": "/images/optimized/hinge-bearing-256.webp",
      "384": "/images/optimized/hinge-bearing-384.webp",
      "390": "/images/optimized/hinge-bearing-390.webp",
      "640": "/images/optimized/hinge-bearing-640.webp",
      "768": "/images/optimized/hinge-bearing-768.webp",
      "800": "/images/optimized/hinge-bearing-800.webp"
    }
  },
  "/images/hinge-flag-leaf.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-flag-leaf-64.webp",
      "96": "/images/optimized/hinge-flag-leaf-96.webp",
      "128": "/images/optimized/hinge-flag-leaf-128.webp",
      "256": "/images/optimized/hinge-flag-leaf-256.webp",
      "384": "/images/optimized/hinge-flag-leaf-384.webp",
      "390": "/images/optimized/hinge-flag-leaf-390.webp",
      "640": "/images/optimized/hinge-flag-leaf-640.webp",
      "768": "/images/optimized/hinge-flag-leaf-768.webp",
      "800": "/images/optimized/hinge-flag-leaf-800.webp"
    }
  },
  "/images/hinge-flag.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      750
    ],
    "variants": {
      "64": "/images/optimized/hinge-flag-64.webp",
      "96": "/images/optimized/hinge-flag-96.webp",
      "128": "/images/optimized/hinge-flag-128.webp",
      "256": "/images/optimized/hinge-flag-256.webp",
      "384": "/images/optimized/hinge-flag-384.webp",
      "390": "/images/optimized/hinge-flag-390.webp",
      "640": "/images/optimized/hinge-flag-640.webp",
      "750": "/images/optimized/hinge-flag-750.webp"
    }
  },
  "/images/hinge-gasket.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-gasket-64.webp",
      "96": "/images/optimized/hinge-gasket-96.webp",
      "128": "/images/optimized/hinge-gasket-128.webp",
      "256": "/images/optimized/hinge-gasket-256.webp",
      "384": "/images/optimized/hinge-gasket-384.webp",
      "390": "/images/optimized/hinge-gasket-390.webp",
      "640": "/images/optimized/hinge-gasket-640.webp",
      "768": "/images/optimized/hinge-gasket-768.webp",
      "800": "/images/optimized/hinge-gasket-800.webp"
    }
  },
  "/images/hinge-grease-nipple.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-grease-nipple-64.webp",
      "96": "/images/optimized/hinge-grease-nipple-96.webp",
      "128": "/images/optimized/hinge-grease-nipple-128.webp",
      "256": "/images/optimized/hinge-grease-nipple-256.webp",
      "384": "/images/optimized/hinge-grease-nipple-384.webp",
      "390": "/images/optimized/hinge-grease-nipple-390.webp",
      "640": "/images/optimized/hinge-grease-nipple-640.webp",
      "768": "/images/optimized/hinge-grease-nipple-768.webp",
      "800": "/images/optimized/hinge-grease-nipple-800.webp"
    }
  },
  "/images/hinge-oil-hole.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1920
    ],
    "variants": {
      "64": "/images/optimized/hinge-oil-hole-64.webp",
      "96": "/images/optimized/hinge-oil-hole-96.webp",
      "128": "/images/optimized/hinge-oil-hole-128.webp",
      "256": "/images/optimized/hinge-oil-hole-256.webp",
      "384": "/images/optimized/hinge-oil-hole-384.webp",
      "390": "/images/optimized/hinge-oil-hole-390.webp",
      "640": "/images/optimized/hinge-oil-hole-640.webp",
      "768": "/images/optimized/hinge-oil-hole-768.webp",
      "1024": "/images/optimized/hinge-oil-hole-1024.webp",
      "1280": "/images/optimized/hinge-oil-hole-1280.webp",
      "1440": "/images/optimized/hinge-oil-hole-1440.webp",
      "1920": "/images/optimized/hinge-oil-hole-1920.webp"
    }
  },
  "/images/hinge-pin-hero.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1920
    ],
    "variants": {
      "64": "/images/optimized/hinge-pin-hero-64.webp",
      "96": "/images/optimized/hinge-pin-hero-96.webp",
      "128": "/images/optimized/hinge-pin-hero-128.webp",
      "256": "/images/optimized/hinge-pin-hero-256.webp",
      "384": "/images/optimized/hinge-pin-hero-384.webp",
      "390": "/images/optimized/hinge-pin-hero-390.webp",
      "640": "/images/optimized/hinge-pin-hero-640.webp",
      "768": "/images/optimized/hinge-pin-hero-768.webp",
      "1024": "/images/optimized/hinge-pin-hero-1024.webp",
      "1280": "/images/optimized/hinge-pin-hero-1280.webp",
      "1440": "/images/optimized/hinge-pin-hero-1440.webp",
      "1920": "/images/optimized/hinge-pin-hero-1920.webp"
    }
  },
  "/images/hinge-pin.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-pin-64.webp",
      "96": "/images/optimized/hinge-pin-96.webp",
      "128": "/images/optimized/hinge-pin-128.webp",
      "256": "/images/optimized/hinge-pin-256.webp",
      "384": "/images/optimized/hinge-pin-384.webp",
      "390": "/images/optimized/hinge-pin-390.webp",
      "640": "/images/optimized/hinge-pin-640.webp",
      "768": "/images/optimized/hinge-pin-768.webp",
      "800": "/images/optimized/hinge-pin-800.webp"
    }
  },
  "/images/hinge-round.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-round-64.webp",
      "96": "/images/optimized/hinge-round-96.webp",
      "128": "/images/optimized/hinge-round-128.webp",
      "256": "/images/optimized/hinge-round-256.webp",
      "384": "/images/optimized/hinge-round-384.webp",
      "390": "/images/optimized/hinge-round-390.webp",
      "640": "/images/optimized/hinge-round-640.webp",
      "768": "/images/optimized/hinge-round-768.webp",
      "800": "/images/optimized/hinge-round-800.webp"
    }
  },
  "/images/hinge-square.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      800
    ],
    "variants": {
      "64": "/images/optimized/hinge-square-64.webp",
      "96": "/images/optimized/hinge-square-96.webp",
      "128": "/images/optimized/hinge-square-128.webp",
      "256": "/images/optimized/hinge-square-256.webp",
      "384": "/images/optimized/hinge-square-384.webp",
      "390": "/images/optimized/hinge-square-390.webp",
      "640": "/images/optimized/hinge-square-640.webp",
      "768": "/images/optimized/hinge-square-768.webp",
      "800": "/images/optimized/hinge-square-800.webp"
    }
  },
  "/images/illustrations/application-control-cabinet.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1448
    ],
    "variants": {
      "64": "/images/optimized/illustrations/application-control-cabinet-64.webp",
      "96": "/images/optimized/illustrations/application-control-cabinet-96.webp",
      "128": "/images/optimized/illustrations/application-control-cabinet-128.webp",
      "256": "/images/optimized/illustrations/application-control-cabinet-256.webp",
      "384": "/images/optimized/illustrations/application-control-cabinet-384.webp",
      "390": "/images/optimized/illustrations/application-control-cabinet-390.webp",
      "640": "/images/optimized/illustrations/application-control-cabinet-640.webp",
      "768": "/images/optimized/illustrations/application-control-cabinet-768.webp",
      "1024": "/images/optimized/illustrations/application-control-cabinet-1024.webp",
      "1280": "/images/optimized/illustrations/application-control-cabinet-1280.webp",
      "1440": "/images/optimized/illustrations/application-control-cabinet-1440.webp",
      "1448": "/images/optimized/illustrations/application-control-cabinet-1448.webp"
    }
  },
  "/images/illustrations/application-trailer-gate.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1448
    ],
    "variants": {
      "64": "/images/optimized/illustrations/application-trailer-gate-64.webp",
      "96": "/images/optimized/illustrations/application-trailer-gate-96.webp",
      "128": "/images/optimized/illustrations/application-trailer-gate-128.webp",
      "256": "/images/optimized/illustrations/application-trailer-gate-256.webp",
      "384": "/images/optimized/illustrations/application-trailer-gate-384.webp",
      "390": "/images/optimized/illustrations/application-trailer-gate-390.webp",
      "640": "/images/optimized/illustrations/application-trailer-gate-640.webp",
      "768": "/images/optimized/illustrations/application-trailer-gate-768.webp",
      "1024": "/images/optimized/illustrations/application-trailer-gate-1024.webp",
      "1280": "/images/optimized/illustrations/application-trailer-gate-1280.webp",
      "1440": "/images/optimized/illustrations/application-trailer-gate-1440.webp",
      "1448": "/images/optimized/illustrations/application-trailer-gate-1448.webp"
    }
  },
  "/images/illustrations/custom-engineering.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1448
    ],
    "variants": {
      "64": "/images/optimized/illustrations/custom-engineering-64.webp",
      "96": "/images/optimized/illustrations/custom-engineering-96.webp",
      "128": "/images/optimized/illustrations/custom-engineering-128.webp",
      "256": "/images/optimized/illustrations/custom-engineering-256.webp",
      "384": "/images/optimized/illustrations/custom-engineering-384.webp",
      "390": "/images/optimized/illustrations/custom-engineering-390.webp",
      "640": "/images/optimized/illustrations/custom-engineering-640.webp",
      "768": "/images/optimized/illustrations/custom-engineering-768.webp",
      "1024": "/images/optimized/illustrations/custom-engineering-1024.webp",
      "1280": "/images/optimized/illustrations/custom-engineering-1280.webp",
      "1440": "/images/optimized/illustrations/custom-engineering-1440.webp",
      "1448": "/images/optimized/illustrations/custom-engineering-1448.webp"
    }
  },
  "/images/illustrations/manufacturing-capability.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1448
    ],
    "variants": {
      "64": "/images/optimized/illustrations/manufacturing-capability-64.webp",
      "96": "/images/optimized/illustrations/manufacturing-capability-96.webp",
      "128": "/images/optimized/illustrations/manufacturing-capability-128.webp",
      "256": "/images/optimized/illustrations/manufacturing-capability-256.webp",
      "384": "/images/optimized/illustrations/manufacturing-capability-384.webp",
      "390": "/images/optimized/illustrations/manufacturing-capability-390.webp",
      "640": "/images/optimized/illustrations/manufacturing-capability-640.webp",
      "768": "/images/optimized/illustrations/manufacturing-capability-768.webp",
      "1024": "/images/optimized/illustrations/manufacturing-capability-1024.webp",
      "1280": "/images/optimized/illustrations/manufacturing-capability-1280.webp",
      "1440": "/images/optimized/illustrations/manufacturing-capability-1440.webp",
      "1448": "/images/optimized/illustrations/manufacturing-capability-1448.webp"
    }
  },
  "/images/illustrations/packaging-shipping.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1448
    ],
    "variants": {
      "64": "/images/optimized/illustrations/packaging-shipping-64.webp",
      "96": "/images/optimized/illustrations/packaging-shipping-96.webp",
      "128": "/images/optimized/illustrations/packaging-shipping-128.webp",
      "256": "/images/optimized/illustrations/packaging-shipping-256.webp",
      "384": "/images/optimized/illustrations/packaging-shipping-384.webp",
      "390": "/images/optimized/illustrations/packaging-shipping-390.webp",
      "640": "/images/optimized/illustrations/packaging-shipping-640.webp",
      "768": "/images/optimized/illustrations/packaging-shipping-768.webp",
      "1024": "/images/optimized/illustrations/packaging-shipping-1024.webp",
      "1280": "/images/optimized/illustrations/packaging-shipping-1280.webp",
      "1440": "/images/optimized/illustrations/packaging-shipping-1440.webp",
      "1448": "/images/optimized/illustrations/packaging-shipping-1448.webp"
    }
  },
  "/images/illustrations/quality-control.png": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1448
    ],
    "variants": {
      "64": "/images/optimized/illustrations/quality-control-64.webp",
      "96": "/images/optimized/illustrations/quality-control-96.webp",
      "128": "/images/optimized/illustrations/quality-control-128.webp",
      "256": "/images/optimized/illustrations/quality-control-256.webp",
      "384": "/images/optimized/illustrations/quality-control-384.webp",
      "390": "/images/optimized/illustrations/quality-control-390.webp",
      "640": "/images/optimized/illustrations/quality-control-640.webp",
      "768": "/images/optimized/illustrations/quality-control-768.webp",
      "1024": "/images/optimized/illustrations/quality-control-1024.webp",
      "1280": "/images/optimized/illustrations/quality-control-1280.webp",
      "1440": "/images/optimized/illustrations/quality-control-1440.webp",
      "1448": "/images/optimized/illustrations/quality-control-1448.webp"
    }
  },
  "/images/packaging-12-14-16-type.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1920
    ],
    "variants": {
      "64": "/images/optimized/packaging-12-14-16-type-64.webp",
      "96": "/images/optimized/packaging-12-14-16-type-96.webp",
      "128": "/images/optimized/packaging-12-14-16-type-128.webp",
      "256": "/images/optimized/packaging-12-14-16-type-256.webp",
      "384": "/images/optimized/packaging-12-14-16-type-384.webp",
      "390": "/images/optimized/packaging-12-14-16-type-390.webp",
      "640": "/images/optimized/packaging-12-14-16-type-640.webp",
      "768": "/images/optimized/packaging-12-14-16-type-768.webp",
      "1024": "/images/optimized/packaging-12-14-16-type-1024.webp",
      "1280": "/images/optimized/packaging-12-14-16-type-1280.webp",
      "1440": "/images/optimized/packaging-12-14-16-type-1440.webp",
      "1920": "/images/optimized/packaging-12-14-16-type-1920.webp"
    }
  },
  "/images/packaging-20-type.jpg": {
    "widths": [
      64,
      96,
      128,
      256,
      384,
      390,
      640,
      768,
      1024,
      1280,
      1440,
      1920
    ],
    "variants": {
      "64": "/images/optimized/packaging-20-type-64.webp",
      "96": "/images/optimized/packaging-20-type-96.webp",
      "128": "/images/optimized/packaging-20-type-128.webp",
      "256": "/images/optimized/packaging-20-type-256.webp",
      "384": "/images/optimized/packaging-20-type-384.webp",
      "390": "/images/optimized/packaging-20-type-390.webp",
      "640": "/images/optimized/packaging-20-type-640.webp",
      "768": "/images/optimized/packaging-20-type-768.webp",
      "1024": "/images/optimized/packaging-20-type-1024.webp",
      "1280": "/images/optimized/packaging-20-type-1280.webp",
      "1440": "/images/optimized/packaging-20-type-1440.webp",
      "1920": "/images/optimized/packaging-20-type-1920.webp"
    }
  }
};
